### ISSUE TITLE
Perf hit when releasing the backup lock due to a range request

### ISSUE THREAD

**Issue by jeremyk-91** [palantir/atlasdb#1668] opened 2017-03-02 12:55 UTC
In #1665 we switched to returning users lock IDs instead of lock entries. However, this causes us to do a range-request on the KVS table for the relevant ID to get the data for the entry, which looks like it caused perf regressions on internal benchmarks. Previously the lock entry had the cell data required for the check-and-set.

I agree with the change (users shouldn't need to know the cell data), but this perf hit is avoidable. A fix probably involves caching this in the lock store or PersistentLockService.

Not sure in practice whether this is a problem though; do we plan on sweeping _that_ repeatedly?

**Comment by SerialVelocity** [comment] 2017-03-02 15:05
I don't this caching is needed at the moment. If we need really good performance for the persistent locks, this probably means we are supporting more lock types than just the backup lock and should be revisited then.

I think the bigger issue is:
  - Why is a single row range scan causing a perf hit?

**Comment by SerialVelocity** [comment] 2017-03-02 15:24
Just a bit more info I found while digging:
  - The single sweep run benchamark went from 8us to 10us.
  - The multiple (x10) sweep run benchmark went from 70us to 80us.

So it looks like the perf it is 1-2us per sweep run in the benchmarks which seems acceptable? (In reality it's per batch of cells to sweep)

**Comment by rhero** [comment] 2017-03-20 13:40
Going to close this out because we're scoping this lock to be really only for backups and it shouldn't be used for persistent locks generally. This regression is small and on an async non-critical operation, so we're not worried about it.

**Closed by rhero** 2017-03-20 13:40 UTC
Labels: component: performance, component: sweep
