### ISSUE TITLE
Cassandra client pool unable to recover when all Cassandra nodes get blacklisted

### ISSUE THREAD

**Issue by jnelson15** [palantir/atlasdb#1407] opened 2017-01-05 18:30 UTC
There have been various examples where Cassandra nodes hit long GCs and OOM, causing the client pools to blacklist all the nodes. In theory we should still be able to make progress when the cluster recovers, but apparently this does not happen until the clients are bounced. I think there are a couple problems here:
- First question is why this is happening. My theory at the moment is a single long GC causes the various clients to all get socket timeouts, blacklist that host, and failover and put disproportionate load on the remaining servers. At the moment we backoff if "pool for this node is fully in use" or "remote cassandra node couldn't talk to enough other remote cassandra nodes to answer". Should we also backoff when we get socket timeouts? Could also probably make the backoff a random exponentional backoff so that a node going down doesn't force all the failovers to happen all at once.
- Second question is why we can't recover from this. This is less clear, but seems like maybe we're not handling all the exceptions in `isInvalidClientConnection` in `CassandraClientPoolingContainer#runWithGoodResource`. For example, if we get a `SocketTimeoutException`, will we put the resource back into the pool? I think eventually the evictor should handle these and remove them from the associated connections from the pool, but have seen examples where the client remained down for a pretty significant amount of time without doing so.

**Comment by rhero** [comment] 2017-01-05 20:31
Tagging @harrybiddle. Have we seen similar behavior with our Jepsen testing? This sounds oddly familiar to issues you hit during early multi-node Cassandra testing.

**Comment by jnelson15** [comment] 2017-01-06 21:08
@clockfort do you see any issue if I add a small backoff in the case that we catch an exception that is `isConnectionException` in `runWithRetryOnHost`? Unless there's a common case where we'd get socket timeouts, seems that they could be indicative of a long GC, heavy load, etc on the host that could help by not continuing to hammer it. This doesn't solve the recovery issue obviously but hopefully can help avoid failing over too quickly to other hosts and creating cascading load issues.

**Comment by jnelson15** [comment] 2017-01-06 22:53
https://github.com/palantir/atlasdb/pull/1420

**Comment by gsheasby** [comment] 2017-01-10 10:26
@jnelson15 are we confident that the backoff in #1420 will solve this issue? Or is it just one part of the story?

**Comment by jnelson15** [comment] 2017-01-10 14:43
The backoff hopefully helps prevent us from getting into that state but still an issue if it does. If we can figure out how to recreate it that would be helpful but so far this has mostly been anecdotal so unclear what the specific cause is here. Hopefully those Jepsen results can help.

**Comment by gsheasby** [comment] 2017-01-10 14:50
We might want to split this issue in two so we can separately track
1) recovering from OOM + restart
2) recovering from a longer-term outage

@tboam for SA

**Comment by jnelson15** [comment] 2017-01-10 18:09
Yeah makes sense. I've tested common case failures like a service getting killed or a node dropping packets, but this seems to be due to some middle-ground where the service is pseudo-responsive -- possibly chain of GCs until finally run out of memory + restart server and we can't recover. Typically the anecdotal cases we've seen have involved the entire cluster getting blacklisted so possibly something related to combination of unresponsive nodes and blacklisted cluster.

**Comment by gsheasby** [comment] 2017-01-11 17:48
// Shifting this to "To do" and assigning Tom to track ticket-splitting.

#1420 has merged and will be released with 0.28.0. The other parts remain to be addressed.

**Comment by tboam** [comment] 2017-01-12 11:30
To recap: when we hit issues talking to Cassandra we've found ourselves get into a bad state where all hosts are blacklisted and so we can't write anything.

We now backoff when we get a SocketTimeoutException and we backoff for a random period to prevent lots of simultaneous calls after a C* node becomes unresponsive.  This has merged and will go out in 0.28.0.

Remaining work is to understand how we can get into a state where all nodes are blacklisted.  If this is a problem with blacklisting we should fix it.  If this is a problem where the whole C* cluster is genuinely unavailable for a period we should get better at recovering from such situations.

There's a few approaches we could take here including, but not limited to, Jepsen testing of C* failures.

Given there's 1 clear direction for this ticket again I'm not going to create a new one, just change the name on this one.

**Comment by jnelson15** [comment] 2017-01-12 16:42
We can handle the general case when all the nodes get blacklisted (even the whole cluster for a short period of time). However, there seems to be an edge case that some production systems have seen that we haven't been able to repro on our side yet. The two cases I've seen have been (1) from the nodes OOM'ing and (2) from an AWS instance getting detached due to cloud weirdness. I've tested both killing and partitioning nodes which works fine. It could just be that it's slow to cleanup our stale connections since the evictor takes a few minutes to go through the pool. However, it sounds like usually people have waited longer than a few minutes to bounce so that's likely not the case.

**Comment by tboam** [comment] 2017-01-13 11:11
Thanks for clarifying.  Understand this ticket now requires investigation to find the root cause before we can fix anything.

How often has this happened?  Trying to establish the priority of this work.

**Comment by jnelson15** [comment] 2017-01-13 14:36
For a stack in a stable state it should hopefully be rare. The last case seemed to be due to large unswept tables causing memory pressure on the nodes. Are we planning on turning sweep on by default in the near future? That would help band-aid this issue as well.

**Comment by tboam** [comment] 2017-01-13 16:29
Yes we are.  This is likely to be on Q1 roadmap and @gsheasby is currently getting up to speed on this work.

**Comment by gmaretic** [comment] 2019-10-08 15:03
This must have been fixed since we are not seeing it anymore

**Closed by gmaretic** 2019-10-08 15:03 UTC
Labels: component: HA, priority: P1

**Comment by harrybiddle** [comment] 2019-10-11 15:11
It's great when that happens.
