### ISSUE TITLE
Flaky test: CassandraDropwizardEteTest

### ISSUE THREAD

**Issue by hsaraogi** [palantir/atlasdb#845] opened 2016-08-25 16:59 UTC
This test has been failing at multiple instances, about 1/2 times recently.

Flaky builds: 
- https://circleci.com/gh/palantir/atlasdb/2231
- https://circleci.com/gh/palantir/atlasdb/2237
- https://circleci.com/gh/palantir/atlasdb/2744

**Comment by gbrova** [comment] 2016-08-26 10:04
Looked into this a bit last night, here's a brain dump of what I tried (LMK if something is unclear): 

 - The `dockerize` step usually takes about 60 seconds waiting for Cassandra to be up, then the first log entry in AtlasDB initialization can take 30 seconds (usually less, sometimes more) to appear. That would leave only 30 seconds for the rest of the initialization (including leader election) to happen. 
 - On my machine, I can consistently reproduce the "Connection refused" (after 2 minute timeout) error by adding load. Having 3 instances of this test running concurrently will almost always cause the timeout. 
 - When this timeout happens locally, there are no AtlasDB log entries on `ete1` - the last line I see is `ete1_1 | 2016/08/26 11:36:41 Connected to tcp://cassandra:9160`. The container can stay in this state for >5 minutes if there is load on the machine. 
 - If I lighten the load by killing some of the other containers (from the other instances of the test), this container "unblocks" and the tests eventually pass. 
 - On my machine, if there is no load, the test always passes. 

Attempted fix: 

 - I tried increasing the timeout to 5 minutes instead of 2 (see branch `feature/increase-docker-timeout`), hypothesizing that tests on Circle fail because we exceed the 2 minute limit when the load is temporarily high.  However, I don't think this helps - about 1/4 runs fail on develop, and so far 2/7 [runs](https://circleci.com/gh/palantir/atlasdb/tree/feature%2Fincrease-docker-timeout) failed. 

Proposed next steps: 

 - Let's look at the container logs (cassandra, ete1, ete2, ete3) for failed tests, maybe that will give us a clue around what's happening in the Circle environment that's different from my local machine.

**Comment by gbrova** [comment] 2016-09-12 19:04
Still seeing this, for example on [build 2652](https://circleci.com/gh/palantir/atlasdb/2652#tests/containers/2). 

This seems to be because sometimes Cassandra doesn't respond and we don't retry. See the [logs for ete1](https://2652-36960637-gh.circle-artifacts.com/2//home/ubuntu/atlasdb/atlasdb-ete-tests/container-logs/cassandra-ha/ete1.log). 

Possible fixes: 

1. Surround [TransactionManagers.create](https://github.com/palantir/atlasdb/blob/develop/atlasdb-ete-tests/src/main/java/com/palantir/atlasdb/AtlasDbEteServer.java#L56) with some retry logic
2. Change `EteSetup` to restart the container if it dies prematurely. 
3. Fix #930 

(3) is the correct solution, but (1) or (2) might be acceptable short-term fixes if this gets annoying.

**Comment by gsheasby** [comment] 2016-09-20 10:17
Possibly related flake with CassandraMultinodeTestSuite: https://circleci.com/gh/palantir/atlasdb/2783

**Comment by rhero** [comment] 2016-11-13 17:11
@harrybiddle did you by chance look at this recently as you fixed up some other Cassandra tests? I'd like to close this one.

**Comment by harrybiddle** [comment] 2016-11-14 12:08
I didn't look at this in particular: we have worked on the code paths that this timeout is coming from, and fixed related issues, but I can't guarantee that this flake is no longer present. Suggest we close this out and open it up again if we observe it in the future.

**Closed by harrybiddle** 2016-11-14 12:08 UTC
Labels: component: testing, priority: P2
