### ISSUE TITLE
Leader Election can retrigger multiple times in certain conditions

### ISSUE THREAD

**Issue by joelea** [palantir/atlasdb#383] opened 2016-04-28 10:36 UTC

**Comment by joelea** [comment] 2016-05-09 18:55
@NeilRickards this is the issue we talked about previously,

We're working on a minimal, local repro - interestingly it looks like the issue does not trigger with postgres.

**Comment by joelea** [comment] 2016-05-25 14:59
Sorry for the lack of updates on this. It's been pushed down the list of priorities but is pretty close to the top after the current KVS and correctness priorities are handled.

**Comment by joelea** [comment] 2016-05-26 10:56
Waiting for the testing infrastructure for #444

**Comment by gbrova** [comment] 2016-06-10 18:07
Sometimes `TransactionManager.runTaskWithRetry` does not correctly retry if a leadership change happened during the transaction, and instead throws a `RuntimeException`.  We are able to consistently reproduce this (manually for now) by shutting down the leader node while a transaction is in progress. 

This doesn't explain the leadership election flurry, but it could explain the problems Neil observed internally.  Will follow up with the internal product team next week.

**Comment by jboreiko** [comment] 2016-06-21 10:36
Blocked on response from internal product @j-baker

**Comment by gsheasby** [comment] 2016-06-21 16:52
Caught up with James. The issue occurred in the following workflow:
- Start up Atlas
- Immediately start pinging it every 100ms

Internal branch is "writes_to_commit_log_are_published"

**Comment by jboreiko** [comment] 2016-06-23 10:54
Blocked on more structured plan for recreating / resolving this issue.

**Comment by jboreiko** [comment] 2016-09-02 17:31
@NeilRickards again expressed interest in getting this tackled, documenting here.

**Comment by NeilRickards** [comment] 2016-09-06 10:47
Jakub will be joining Salt+Lime once Phoenix has released their LTS version, and getting this working will be his first priority.

**Comment by gbrova** [comment] 2016-09-06 15:37
@NeilRickards Sounds good - I'm happy to be the point of contact on this and help Jakub iron out any lingering issues.

**Comment by gsheasby** [comment] 2016-11-15 15:23
Is @jkozlowski still working on this?

**Comment by NeilRickards** [comment] 2016-11-15 15:57
He was until yesterday.  Rick's pulled him off to work on Synchronizer for the moment

**Comment by rhero** [comment] 2017-01-26 00:28
@harrybiddle @gsheasby - do you know if this issue is still present with our implementation of the Timelock service? It might be worth working with @NeilRickards and running their failing test with our Timelock server.

**Comment by gsheasby** [comment] 2017-01-26 10:34
CC @jeremyk-91 who is in the best place to answer.

Intuitively, the workflow James described (start Atlas, start pinging it) should go away if we're starting AtlasDB as a separate service and then pinging it. Products using AtlasDB in this way will probably need some way of coping with waking up before AtlasDB does, if we want to avoid introducing an extra "service ordering" constraint.

**Comment by harrybiddle** [comment] 2017-01-26 18:35
Uncertain if this does appear; but the Jepsen tests are exercising constantly hitting a service while leadership election does occur, so tackling #1359 would answer this thread.

I've just put up a PR #1510 so that our Jepsen tests additionally start hitting the timelock server before it starts.

**Comment by rhero** [comment] 2017-03-20 13:50
@NeilRickards I think this might actually be fixed now with the timelock server. You guys should be able to use a Timelock docker image to see if you can reproduce this. We aren't publishing it right now, but if you guys are interested in finding out if Timelock resolves the issue, feel free to reach out.

**Comment by gsheasby** [comment] 2017-05-16 12:13
Root-caused in #1799 - this happens due to Feign retrying requests (e.g. getFreshTimestamps) with very high frequency (50x per second observed), causing the Paxos process to struggle.

**Closed** 2018-12-07 16:05 UTC
Labels: component: HA, priority: P1, type: bug
