### ISSUE TITLE
Validation of LeaderAndTerm is too strict

### ISSUE THREAD

**Issue by jeremyk-91** [palantir/atlasdb#1292] opened 2016-11-25 20:31 UTC
When a new leader is elected, we don't update the leader info (which is used by individual classes to decide whether to serve requests or not) if the term is not newer than what's already there. Ordinarily, this is correct because terms are increasing. However, this is incorrect in a specific case, where all nodes in a cluster crash. We have from the Atomix API docs (for [Election](http://atomix.io/atomix/api/latest/io/atomix/group/election/Election.html)):

> The Term.term() is guaranteed to be unique and monotonically increasing _throughout the lifetime of a group._ (emphasis mine)

But if all nodes in a cluster crash or are otherwise stopped, (if I'm not wrong) the group's lifetime is considered to have ended. This is definitely the case on a 1 node cluster:

```java
INFO  [2016-11-25 20:29:56,025] io.atomix.copycat.server.state.ServerContext: localhost/127.0.0.1:8700 - Transitioning to LEADER
INFO  [2016-11-25 20:29:56,028] io.atomix.copycat.server.state.ServerContext: localhost/127.0.0.1:8700 - Found leader localhost/127.0.0.1:8700
INFO  [2016-11-25 20:29:56,035] io.atomix.copycat.server.state.ServerStateMachine: localhost/127.0.0.1:8700 - Installing snapshot 1
INFO  [2016-11-25 20:29:56,078] io.atomix.copycat.server.CopycatServer: Server started successfully!
INFO  [2016-11-25 20:29:56,112] io.atomix.copycat.client.session.ClientSession: Registered session 208
INFO  [2016-11-25 20:29:56,153] com.palantir.atlasdb.timelock.TimeLockServer: Not setting the leader to LeaderAndTerm{term=0, leaderId=384f2ea7-2152-4fd9-9f6d-9dea455e2e11} since it is not newer than the current leader LeaderAndTerm{term=8, leaderId=2a332a28-0984-4f03-9387-7f6bed4e7467}
```

In this case it seems that Atomix starts again from 0, and so no one will touch the existing LeaderAndTerm. This means the ID remains as that of the leader immediately before the cluster crashed, and this seems to be some UUID that's freshly generated i.e. **no one is the leader**, which means that timestamps and locks cannot be issued at all.

Workaround/recovery: open a separate atomix client, have it join the cluster and explicitly clear the leader value.

If Timelock was fully in use I'd lean towards a P0 (especially if it was compulsory, as single node clusters are completely unusable), but since it's not I've put it as P1 for now.

**Comment by harrybiddle** [comment] 2016-11-25 21:08
I've just tried this out on the five-node cluster case:

- Bring up five nodes
- Restart the leader
- Kill all the nodes at the same time
- Bring them all back up at the same time

Confirmed that no nodes have taken leadership, and I see the same error message in the logs of the one that tried to take leadership.

**Comment by jeremyk-91** [comment] 2016-11-25 21:10
@harrybiddle Thanks a lot for doing this this late, you're too kind! :)

I'm happy to work on a fix next week - as I've said since this isn't in mainline usage it's important, but not "stop-the-world" important.

**Comment by tpetracca** [comment] 2016-11-28 18:12
Linking the comment I left on a different PR https://github.com/palantir/atlasdb/pull/1262#issuecomment-263347050

> Was thinking about this. Can we not just do what we've always done for timestamp service and instead of keeping info about leader and term just store a local version of what we believe the current value of the distributed long and any time it's not that value anymore assume that we lost "leadership"?

**Comment by rhero** [comment] 2016-11-29 15:27
Yeah we need to do this one before the timelock server is usable.

**Comment by SerialVelocity** [comment] 2016-11-30 13:58
Asked about this in the atomix gitter room. Waiting on a response.

**Comment by markelliot** [comment] 2016-12-07 21:55
I think if you switch to deciding if you're still the leader by checking that, when you believe you're the leader, the ceiling you think you own is unchanged, this problem would not apply.

**Comment by gsheasby** [comment] 2017-01-06 16:39
@SerialVelocity any response?

**Comment by SerialVelocity** [comment] 2017-01-09 15:25
We're probably switching to a different implementation because of other issues with atomix so we can probably close this ticket. @jeremyk-91 for SA

**Closed** 2017-01-10 15:16 UTC
Labels: component: timelock, priority: P0, type: bug
