### ISSUE TITLE
MultipleRunningTimestampServiceError isn't as useful as it could be

### ISSUE THREAD

**Issue by tpetracca** [palantir/atlasdb#996] opened 2016-09-27 15:03 UTC
Internal PDS-45797

Seeing occurrences of this error and we're about 99% sure that there are no other timestamp services that have spun up or run against this keyspace while the current atlas/timestamp service was up.  I had a theory a while ago about what could be happening here and the logging around this makes it hard to know.

In CassandraTimestampBoundStore we keep track of `lastWriteException` which just holds the last exception seen by a CAS attempt at placing the new upper limit.  It would be useful to actually log this exception either when it happens or when you hit an occurrence of the CAS failing due to mismatch of value in the DB.

Generally I have a theory that we have a failure mode where we do a CAS and it succeeds on the Cassandra side, but for whatever reason we get an exception client side (thus not updating our in-memory limit).  Thus the next attempted CAS fails with a mismatch.

**Comment by tpetracca** [comment] 2016-09-27 15:03
@gauravtiwari89

**Comment by hsaraogi** [comment] 2016-10-06 14:36
Duplicate of #1000

**Closed by hsaraogi** 2016-10-06 14:36 UTC
