### ISSUE TITLE
Cassandra Create Table Isn't Idempotent

### ISSUE THREAD

**Issue by tpetracca** [palantir/atlasdb#429] opened 2016-05-11 04:37 UTC
Every service running against a cassandra keyspace instantiates its own CassandraKeyValueService.  Part of the init for an instance of this class involves checking for the existence of its keyspace and it's various tables in cassandra.  If a table doesn't exist it then attempts to create it.  This means that if multiple services are started up against the same keyspace/schema at once (like we do when deploying for high availability with timestamp/lock leadership election) that we can potentially have multiple services see a missing table and attempt to call KVS.createTable for the same table at roughly the same time.

Normally this would be okay, but in 2.1 cassandra introduced the concept of each table having a cf_id.  Part of this change has made the cassandra create table/cf call non-idempotent so by having two separate services call createTable at the same time cassandra enters a weird state where it knows both column families exist, will support reads/writes into one of them, but later when bouncing switches over to the other cf_id.  See [CASSANDRA-9424](https://issues.apache.org/jira/browse/CASSANDRA-9424) and  [CASSANDRA-9933](https://issues.apache.org/jira/browse/CASSANDRA-9933).  We need to make sure that only one service is capable of actually executing these createTable calls when multiple are started up and sense a table doesn't exist.

@joelea for SA

I would consider this a P0 as it is preventing the usage of atlas in "HA mode" in the field.

**Comment by joelea** [comment] 2016-05-11 09:31
Did we make any progress on the fix or this in a US timezone? We'll be working on a fix in London and it would be good to avoid duplicating any work.

**Comment by jboreiko** [comment] 2016-05-11 15:42
Current update: @joelea, @gbrova 

As this issue currently stands there appear to be two possible solutions:

1) Downgrade cassandra to 1.2 and/or 2.0 which would appear to not suffer from the problem (this will of course require verification beyond cassandra tickets) - the introduction of concurrent schema modifications in 1.2 with https://issues.apache.org/jira/browse/CASSANDRA-1391 and the fix for a related issue to change the ID generation which breaks this feature - https://issues.apache.org/jira/browse/CASSANDRA-5202

2) Create a method for ensuring that a single node is executing CREATE for a given table.  This would result in a 'at most once' style protocol and would require some methodology for recovery if a bad state is reach.  A simple version of this would require an initial setup step of a vanilla cassandra to contain a table_creation_lock table on which nodes would put unless exists the table name and a unique node id.  The winner would then be responsible for creating the relevant table.  The failing here being that that node could be lost prior to creating the table requiring some form of repair.  If we believe this case to be rare then we could have the repair step be manual.

**Comment by clockfort** [comment] 2016-05-11 18:04
dupe of 431 which I forgot to hit send on (but is much more specifically written)

**Closed by clockfort** 2016-05-11 18:04 UTC
Labels: priority: P0, type: bug
