### ISSUE TITLE
Possible deadlock in LockServiceImpl

### ISSUE THREAD

**Issue by jeremyk-91** [palantir/atlasdb#1715] opened 2017-03-16 23:43 UTC
See internal tickets PDS-50301, PDS-50487, PDS-50490.

There seem to be issues with calls to the lock service blocking indefinitely. Furthermore in PDS-50487 we witnessed this occur for a single node embedded timestamp and lock service, so this is not peculiar to TimeLock either.

For example, redacted version of a thread dump taken in PDS-50487:

```
FOO waiting to lock() LockRequest{lockCount=1, firstLock=LockDescriptor [hex string]=READ, lockTimeout=SimpleTimeDuration{120 seconds}, lockGroupBehavior=LOCK_ALL_OR_NONE, blockingMode=BLOCK_INDEFINITELY_THEN_RELEASE} starting at (5 HOURS AGO)
for requesting thread BAR
```

PDS-50490 indicates that this can occur even if we don't block indefinitely.

In many cases, bouncing the AtlasDB client / TimeLock Server will "fix" the issue, but that's obviously not a long-term solution.

**Comment by jeremyk-91** [comment] 2017-03-17 00:54
Massive wild guess: could OkHttp retries be confounding us? We're using OkHttp 2.5.0 which features connection retries on a read timeout (subsequently removed in 3.3, but present in our version). In theory, this could result in a queue of requests which are never answered if a single response is lost / times out.

1. I make a request A
2. A read timeouts, but the lock request was made
3. I make a request B
4. B read timeouts because it's blocked on A, and the read timeout is less than the lock expiry
5. (...)

So what we could try is deploying a version with connection retries disabled?

**Comment by jeremyk-91** [comment] 2017-03-17 15:57
A candidate for the above can be found on the branch `jkong/no-retry-36plus1`.

**Comment by rhero** [comment] 2017-03-20 14:07
Closing this as a dupe of #1680.

**Closed by rhero** 2017-03-20 14:07 UTC
Labels: priority: P1, type: bug
