### ISSUE TITLE
Support retrieving zero columns in a range request

### ISSUE THREAD

**Issue by ash211** [palantir/atlasdb#417] opened 2016-05-09 21:17 UTC
Filing per @schlosna 

@leeavital to add more details, but it should be possible to pull no columns from a `RangeRequest` by doing something like  `.retainColumns(ColumnSelection.none())`

**Comment by schlosna** [comment] 2016-05-09 21:42
For a bit more context, there is definitely some unexpected behavior if one passes an empty iterable/collection to `com.palantir.atlasdb.keyvalue.api.RangeRequest.Builder#retainColumns(java.lang.Iterable<byte[]>)` this will actually trigger selecting all columns per the following is currently in `com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueService#getRangeWithPageCreator` 

```
        final ColumnSelection selection = rangeRequest.getColumnNames().isEmpty() ? ColumnSelection.all()
                : ColumnSelection.create(rangeRequest.getColumnNames());
```

as well as similar places:
* `com.palantir.atlasdb.keyvalue.api.RangeRequests#extractColumnSelection`
* `com.palantir.atlasdb.keyvalue.cassandra.CQLKeyValueService#getRangeWithPageCreator`
* `com.palantir.atlasdb.keyvalue.jdbc.JdbcKeyValueService#getPageWithValues`
* `com.palantir.example.profile.schema.generated.UserProfileTable.CookiesIdxTable#getRange`

**Comment by clockfort** [comment] 2016-05-09 22:26
Sounds god, just make sure to keep it so that default/ entirely unspecified rangeRequest column selection still means all, since that makes sense. (aka user has chosen no filter, give them back everything)

**Comment by schlosna** [comment] 2016-05-09 22:51
From @leeavital on #417 :

I'm doing a range request on a table with fairly large column components. All of the information I care about is in the row component, so I want to tell the range request to retrieve zero-components. This is, however, impossible because passing a `ColumnSelection` equal to `null` will request all of the columns.

Would it be possible to add a `ColumnSelection.none()`?

**Comment by gsheasby** [comment] 2016-07-26 10:46
This makes sense, but we probably won't get to fixing it any time soon, so closing as won't fix. Happy to reconsider if we've got the priority wrong on this one.

**Closed by gsheasby** 2016-07-26 10:46 UTC
Labels: wontfix
