### ISSUE TITLE
Would like to be able to stream batchingvisitableviews

### ISSUE THREAD

**Issue by j-baker** [palantir/atlasdb#883] opened 2016-09-01 08:54 UTC
BatchingVisitableView is a class ripe for being able to stream in the Java 8 style, but this is hard to implement because it's in a Java 6 package. It'd be great if we could determine whether it really needs to be Java 6 specific, and consequently allow it to be streamed.

For my specific use case where 'stream-like' isn't sufficient; there's code which looks like:

    SetMultimap<Key, Value> toReturn = new HashMap<>();
    someAtlasTable.getAllRowsUnordered().forEach(row -> {
        Key key = row.getRowName().getKey();

        for (SomeAtlasTableColumnValue value : row.getColumnValues()) {
            Value value = new Value.Builder()
                 .setFirstComponent(row.getFirstComponent())
                 .setSecondComponent(row.getSecondComponent())
                 .build();

            toReturn.put(key, value);
        }
    });
    return toReturn;

where it would be really nice to be able to do

    return KeyedStream.of(someAtlasTable.getAllRowsUnordered().stream())
        .mapKeys(row -> row.getRowName().getKey())
        .flatMap(row -> row.getColumnValues().stream())
        .map(value -> new Value.Builder()
            .setFirstComponent(value.getFirstComponent())
            .setSecondComponent(value.getSecondComponent())
            .build())
        .collectToSetMultimap();

**Comment by gbrova** [comment] 2016-09-07 10:30
Possible duplicate of #381 ?

This is not a priority right now.

**Closed by gbrova** 2016-09-07 10:30 UTC
