### ISSUE TITLE
Spammy Cassandra logs 

### ISSUE THREAD

**Issue by shashiadi** [palantir/atlasdb#688] opened 2016-07-15 13:18 UTC
Seeing the following warning logged a bazillion times -- logs > DB size. 
``
WARN  [2016-07-14 14:56:59,851] com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPool: Cluster not fully initialized, not routing query to correct host as not token map found.
``
IL 251781 for a repro.

Relates to #634 but I repro'd on a 3 node guy.

**Comment by rhero** [comment] 2016-07-15 13:20
@clockfort for SA. Any obvious reason why this would now show up on a 3 node cluster?

**Comment by jboreiko** [comment] 2016-07-19 13:05
I just saw this again with a 3 node cluster: IL 251781 for a repro -- shared with the Heroic one.  Moved from #634

**Comment by clockfort** [comment] 2016-07-19 19:39
@jboreiko your issue on IL 251781 is not related to #634 ; I looked at your MP logs, and it can't grab new token mappings because it can't talk to your cluster over SSL correctly. Your issue may be one that came about after a newer internal version of Cassandra started forcing two-way SSL and the automation tools for creating new stacks, etc, may not set things up 100% correctly anymore.

**Comment by gsheasby** [comment] 2016-07-26 11:01
Closing, not a bug in this case.

**Closed by gsheasby** 2016-07-26 11:01 UTC
