### ISSUE TITLE
probabilityDistributionIsNotUniform metric seems to be getting re-registered every minute

### ISSUE THREAD

**Issue by a-k-g** [palantir/atlasdb#2914] opened 2018-01-24 10:56 UTC
When using Atlas 0.73.1, the following `WARN` log line appears every minute:

```
Replacing the metric [ {} ]. This will happen if you are trying to re-register metrics or have two tagged metrics with the same name across the application.
```
metricName "probabilityDistributionIsNotUniform"

**Comment by hsaraogi** [comment] 2018-01-24 10:57
Duplicate of #2885.

**Closed by hsaraogi** 2018-01-24 10:57 UTC
