### ISSUE TITLE
Gradle task to ensure schema code is up to date

### ISSUE THREAD

**Issue by gsheasby** [palantir/atlasdb#703] opened 2016-07-20 08:17 UTC
Motivated by @jboreiko's comment on #647.

"Motivated by the changes in #600, I decided to ensure our generated schema code was in fact up to date. If I have a moment may add a gradle task to ensure this occurs."

**Comment by jboreiko** [comment] 2016-07-21 09:59
After poking around for it there appears to be some gradle task for it, though it does not appear to contain any references to schemas.  So this may be as simple as add the appropriate classes.

**Comment by gsheasby** [comment] 2016-07-26 10:40
./gradlew generateSchemas

**Comment by jboreiko** [comment] 2016-08-01 17:54
I don't believe as it currently stands that that method does anything (as you'll notice from the empty schema block, this is why it doesn't actually run on the gradle build).

**Comment by hsaraogi** [comment] 2016-10-06 14:48
Duplicate of #612

**Closed by hsaraogi** 2016-10-06 14:48 UTC
