### ISSUE TITLE
Upgrade from gradle-java-distribution to sls-packaging

### ISSUE THREAD

**Issue by schlosna** [palantir/atlasdb#1644] opened 2017-02-23 15:49 UTC
We should upgrade from `com.palantir.gradle.javadist:gradle-java-distribution:1.3.0` to `gradle.plugin.com.palantir.sls-packaging:gradle-sls-packaging:2.0.0`, see https://github.com/palantir/sls-packaging/releases

**Comment by jeremyk-91** [comment] 2017-02-27 11:08
Closing out as duplicate of #1612.

**Closed by jeremyk-91** 2017-02-27 11:08 UTC
Labels: component: timelock
