### ISSUE TITLE
Make Cassandra (KVS) Tracing Directly Configurable

### ISSUE THREAD

**Issue by tpetracca** [palantir/atlasdb#2257] opened 2017-08-14 17:19 UTC
Issue title is bad, sorry. Basically I want to be able to set my tracing configuration via a live-reloadable part of my overall Atlas configuration. I don't want it to be a magic separate file that is looked for in a magic place by my governing process.

**Comment by gsheasby** [comment] 2017-08-21 11:11
Closing as a duplicate of #1307 (which, incidentally, is tracked as a "dumb bug" that we'd like to fix before 1.0-ing).

**Closed by gsheasby** 2017-08-21 11:11 UTC
