### ISSUE TITLE
We should create a globally consistent OBJECT_MAPPER

### ISSUE THREAD

**Issue by SerialVelocity** [palantir/atlasdb#665] opened 2016-07-12 13:36 UTC
One for YAML, one for JSON?

Take a look at AtlasDbConfiguredCommand, and AtlasDbConfigs. Problem is we can serialise and deserialise things in different ways depending on how the object mappers are set up.

**Comment by schlosna** [comment] 2016-07-12 15:08
+1 as the Atlas CLI cannot currently deserialize certain configs.

**Comment by gsheasby** [comment] 2016-07-14 10:30
Duplicate of #664

**Closed by gsheasby** 2016-07-14 10:30 UTC
