### ISSUE TITLE
AtlasDB allows creation of keyspace on wrong replication factor - but then complains about it while trying to access it

### ISSUE THREAD

**Issue by harishutd** [palantir/atlasdb#931] opened 2016-09-12 09:53 UTC
Repro Steps:
1. User in atlas-client has replication factor 3 on single node and tries creating keyspace
2. Keyspace is created fine and on trying to do some operations on keyspace it complains that java.lang.UnsupportedOperationException: Your current Cassandra keyspace (<product>) has a replication factor not matching your Atlas Cassandra config…
3. User tries changing replication factor to 1 in config and still doesn't help as keyspace was created with RF 3.

I think what happened here is that atlas didn't guard correctly against creating the keyspace when the config was inconsistent (rf 3 on a single node)

**Comment by tpetracca** [comment] 2016-09-12 11:12
It also sounds like the error message is incorrect.  Your keyspace RF and config were matching, but Atlas is sad about it because your cluster doesn't have enough nodes to actually support the desired RF.

**Comment by tpetracca** [comment] 2016-09-12 11:12
We should probably fail pre-keyspace creation here.

**Comment by jboreiko** [comment] 2016-09-12 13:56
It might be a fine optimization to assume that the KVS is given access to all of the cass nodes and therefore can guess the expected number of nodes and reject impossible RFs in a config check.  This assumption could prove to be false in a possible (but likely unreasonable) configuration.

**Comment by tpetracca** [comment] 2016-09-12 14:02
The only case where we can't infer the nodes is when people don't use a consistent rpc_port across all nodes.  In this case you're required to specify all nodes in your configuration else we throw an exception in the token range check on startup.

**Comment by rhero** [comment] 2016-11-13 16:45
Although slightly different, seems to be very much related to #701, Impossible RF should result in immediate failure of C* KVS.

Are people okay with closing this one out as a dupe, or are these different enough to warrant keeping separate?

**Comment by jboreiko** [comment] 2016-11-15 23:33
These seem the same, feel free to close out as dup.

**Comment by rhero** [comment] 2016-11-15 23:35
Closing out as dupe of #701.

**Closed by rhero** 2016-11-15 23:35 UTC
Labels: priority: P2, type: bug
