### ISSUE TITLE
Backup lock

### ISSUE THREAD

**Issue by rhero** [palantir/atlasdb#852] opened 2016-08-26 10:21 UTC
In order to prevent out of transaction operations (such as Sweep) from corrupting backups that are in progress, we need to introduce a lock for backups and kvs.delete/truncate operations. 

The idea is that all delete/truncate operations would be protected by a lock. We would acquire the lock before taking a backup and then release it at the conclusion of the logical backup. This could negatively impact services that rely on the ability to truncate, but those services should probably change their behavior.

Need to consider what happens if we lose the lock right before delete or backup (if using expiring lock), and also following up with existing products using non-transactional deletes.

@clockfort @tpetracca for SA.

**Comment by rhero** [comment] 2016-11-18 00:34
We haven't prioritized this because people still aren't running sweep by default and aren't regularly taking backups.

**Comment by tkleingarn** [comment] 2016-11-30 00:13
@rhero we've seen a number of support tickets filed as a result of failed backups caused by sweep running during the backup.  This is contributing to a wider and unfounded perception that atlasdb is generally unstable.  Could we bump up the priority on this work?

For our application, our current recommendation is to configure __ATLASDB_SWEEP_BANNED_TIMES in our application to prevent execution of sweep during a backup.  The two issues I’m now aware of:

1. On Oracle, an ORA-01466 error occurs when sweep truncates the sweep__progress table (example: QA-94375).
2. On Postgres, pgdump is unable to acquire a lock on the sweep__progress table (example: PDS-46155).

Adding a couple of other tickets that were root caused to this as well (PDS-47347, PDS-41742).

**Comment by rhero** [comment] 2016-11-30 11:34
Incredible coincidence, but John was taking a look at this last night. We'll get to it before holiday break.

**Comment by tkleingarn** [comment] 2016-12-07 01:56
Which one of these tracks the actual fix?  I think this is a dupe of https://github.com/palantir/atlasdb/pull/1011

**Comment by rhero** [comment] 2016-12-07 10:56
Hey @tkleingarn - #1011 is the pull request that will fix this issue. Normally our issues will have one or more PRs that are associated with fixing them. We try to keep technical discussion to the PRs and then priority, requirements, etc. on the actual issue.

**Comment by gsheasby** [comment] 2016-12-09 20:50
An update as I know people are following this issue: we identified some correctness issues with the initial solution (#1011).

We ran out of time for this in 2016, but this pull request will be replaced with a number of smaller PRs from the first week of January.

**Comment by rhero** [comment] 2017-01-25 17:00
Moving to in progress as we've been working on this since the start of January.
- #1435 contains the CAS feature needed for the backup lock impl
- #1400 contains the new backup lock implementation
- Then need to add testing of Sweep using the backup lock

**Closed** 2017-02-13 18:00 UTC
Labels: priority: P1
