### ISSUE TITLE
Allow RangeRequests to specify no-columns

### ISSUE THREAD

**Issue by leeavital** [palantir/atlasdb#418] opened 2016-05-09 21:35 UTC
I'm doing a range request on a table with fairly large column components. All of the information I care about is in the row component, so  I want to tell the range request to retrieve zero-components. This is, however, impossible because passing a ColumnSelection equal to `null` will request all of the columns.

Would it be possible to add a  `ColumnSelection.none()`?

**Comment by schlosna** [comment] 2016-05-09 22:50
Dupe of #417

**Closed by schlosna** 2016-05-09 22:50 UTC
