### ISSUE TITLE
Lockstamp clients don't deal with redirects gracefully

### ISSUE THREAD

**Issue by leeavital** [palantir/atlasdb#721] opened 2016-07-25 20:44 UTC
I had a leader block that looked like:

```
  leader:
    quorumSize: 1
    localServer: "https://localhost:8443/foo/api/"
    leaders: [ "https://localhost:8443/foo/api/" ]
```

But all of the routes under `/foo/api` redirected to an authentication server. This manifested itself with a not-so-helpful stacktrace:

```
WARN  [2016-07-25 20:40:20,739] com.palantir.atlasdb.transaction.impl.AbstractTransactionManager: RuntimeException while processing transaction.
! java.lang.NullPointerException: null
! at com.sun.proxy.$Proxy55.getFreshTimestamp(Unknown Source) ~[na:na]
! at com.palantir.atlasdb.transaction.impl.SnapshotTransactionManager.setupRunTaskWithLocksThrowOnConflict(SnapshotTransactionManager.java:125) ~[atlasdb-impl-shared-0.8.0.jar:na]
! at com.palantir.atlasdb.transaction.impl.SerializableTransactionManager.setupRunTaskWithLocksThrowOnConflict(SerializableTransactionManager.java:30) ~[atlasdb-impl-shared-0.8.0.jar:na]
! at com.palantir.atlasdb.transaction.impl.SnapshotTransactionManager.runTaskWithLocksThrowOnConflict(SnapshotTransactionManager.java:120) ~[atlasdb-impl-shared-0.8.0.jar:na]
! at com.palantir.atlasdb.transaction.impl.SerializableTransactionManager.runTaskWithLocksThrowOnConflict(SerializableTransactionManager.java:30) ~[atlasdb-impl-shared-0.8.0.jar:na]
! at com.palantir.atlasdb.transaction.impl.AbstractLockAwareTransactionManager.runTaskThrowOnConflict(AbstractLockAwareTransactionManager.java:92) ~[atlasdb-impl-shared-0.8.0.jar:na]
! at com.palantir.atlasdb.transaction.impl.AbstractTransactionManager.runTaskWithRetry(AbstractTransactionManager.java:36) ~[atlasdb-client-0.8.0.jar:na]
! at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_45]
! at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_45]
! at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_45]
! at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_45]
!````

**Comment by joelea** [comment] 2016-07-26 12:29
Hey @leeavital,

I agree the stacktrace is sucky. Have you managed to work around this or do we need to do some more work to get this working for you?

**Comment by leeavital** [comment] 2016-09-10 18:48
Hey @joelea -- sorry about responding so late. It turns out I was setting up auth in the wrong way. 

I eventually figured out that I needed to leave endpoints unauthed, the stack trace just meant that it took way too long to figure it out.

**Comment by jboreiko** [comment] 2016-09-20 11:05
Closing as duplicate of tasks carried out for #516 and an internal ticket about switching to auth endpoints.

**Closed by jboreiko** 2016-09-20 11:05 UTC
Labels: type: bug
